### ISSUE TITLE
Not working on servers

### ISSUE THREAD

**Issue by zmanten** [DuelMonster/MinersAdvantage#52] opened 2020-08-01 01:13 UTC
#### Issue description:
idk if this is something I'm doing wrong but since I have  exhausted every other resource and this seem to be my last chance at getting an answer: here I am. I can't get miners advantage to work on any servers. We have it installed on both client and server, it works in singleplayer, and we did not change the config. Is there something in the config that needs to be changed? It looks like it is all right. 
#### What happens:
Miners advantage does not work at all on forge servers, in version 1.12.2 AND 1.16.1
#### What you expected to happen:
For it to work
#### Does this issue occur on a server or single player world?

- [ x] Server
- [ ] Client Only

#### Steps to reproduce:
1. install Miners Advantage 1.16.1 on client and forge server
2.  attempt to use miners adv on server
3. fail, spend 3 hours trying to fix it, cri

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: 1.16.1-1.7.0.36
- Forge: 1.16.1-32.0.88 (This is not the latest version because Immersive engineering doesn't work on 89+. I tried MinersAdv with 32.0.97 and it did not work either)
- Minecraft: 1.16.1

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
PASTE_HERE
```
</details>

**Comment by herrleinIT** [comment] 2020-09-12 14:31
I think i know where the problem is.
I use Minecraft 1.16.2 with Forge 33.0.32 on a Ubuntu 18.04 System and got a crash too

The Problem is the dependency on de.erdbeerbaerlp.guilib.McMod in combination with a Forge dedicated Server enviroment. Ok, GUI on a headless server makes no sense to me :)
Maybe it is possible to remove the dependency in Advanced Miner in a dedicated Server enviroment.

`[main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
[main/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class de.erdbeerbaerlp.guilib.McMod
java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER`

Edit 28.09.2020
`Build: 1.16.2-1.6.3.151
    fix: server crash issue due to config GUI changes in last version`
Fixed the problem for me.

**Comment by DuelMonster** [comment] 2020-09-28 19:54
Fixed in version 1.16.2-1.6.3.151 and included in version  1.16.3-1.7.3.153

**Closed as completed by DuelMonster** 2020-09-28 19:54 UTC
Labels: Type: Bug, PRIORITY: #1, Status: Confirmed, Status: Accepted, MC Version: 1.16.2
